project_id = "iientxeipzodovkgnwgh"

[functions.send-contact-notification]
verify_jwt = false

[functions.import-remote-image]
verify_jwt = false

[functions.generate-research-image]
verify_jwt = false

[functions.upload-content-image]
verify_jwt = false

[functions.update-project-stats]
verify_jwt = false
